//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace netServicioSAP.ServiceReference1
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos", ConfigurationName = "ServiceReference1.ImportacionPesosPedidos_OS")]
    public interface ImportacionPesosPedidos_OS
    {

        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación ImportacionPesosPedidos_OS no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse ImportacionPesosPedidos_OS(netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://sap.com/xi/WebService/soap1.1", ReplyAction = "*")]
        System.Threading.Tasks.Task<netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse> ImportacionPesosPedidos_OSAsync(netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ImportacionPesosPedidosTypeControlProceso controlProcesoField;

        private ImportacionPesosPedidosTypeCabecera cabeceraField;

        private ImportacionPesosPedidosTypeDetalleCabecera[] detallesCabeceraField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ImportacionPesosPedidosTypeControlProceso ControlProceso
        {
            get
            {
                return this.controlProcesoField;
            }
            set
            {
                this.controlProcesoField = value;
                this.RaisePropertyChanged("ControlProceso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosTypeCabecera Cabecera
        {
            get
            {
                return this.cabeceraField;
            }
            set
            {
                this.cabeceraField = value;
                this.RaisePropertyChanged("Cabecera");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DetalleCabecera", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosTypeDetalleCabecera[] DetallesCabecera
        {
            get
            {
                return this.detallesCabeceraField;
            }
            set
            {
                this.detallesCabeceraField = value;
                this.RaisePropertyChanged("DetallesCabecera");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProceso : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoCompaniaField;

        private string codigoSistemaField;

        private string codigoServicioField;

        private string procesoField;

        private string resultadoField;

        private ImportacionPesosPedidosTypeControlProcesoRespuesta[] respuestaField;

        private ImportacionPesosPedidosTypeControlProcesoERP[] eRPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoCompania
        {
            get
            {
                return this.codigoCompaniaField;
            }
            set
            {
                this.codigoCompaniaField = value;
                this.RaisePropertyChanged("CodigoCompania");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CodigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("CodigoSistema");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string CodigoServicio
        {
            get
            {
                return this.codigoServicioField;
            }
            set
            {
                this.codigoServicioField = value;
                this.RaisePropertyChanged("CodigoServicio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Proceso
        {
            get
            {
                return this.procesoField;
            }
            set
            {
                this.procesoField = value;
                this.RaisePropertyChanged("Proceso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Respuesta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public ImportacionPesosPedidosTypeControlProcesoRespuesta[] Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public ImportacionPesosPedidosTypeControlProcesoERP[] ERP
        {
            get
            {
                return this.eRPField;
            }
            set
            {
                this.eRPField = value;
                this.RaisePropertyChanged("ERP");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoRespuesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string observacionField;

        private ImportacionPesosPedidosTypeControlProcesoRespuestaMensaje[] mensajeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensaje", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosTypeControlProcesoRespuestaMensaje[] Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoRespuestaMensaje : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string identificadorField;

        private string estadoField;

        private string faseField;

        private string errorField;

        private ImportacionPesosPedidosTypeControlProcesoRespuestaMensajeDetallesDetalle[] detallesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
                this.RaisePropertyChanged("Identificador");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detalle", typeof(ImportacionPesosPedidosTypeControlProcesoRespuestaMensajeDetallesDetalle), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosTypeControlProcesoRespuestaMensajeDetallesDetalle[] Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
                this.RaisePropertyChanged("Detalles");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoRespuestaMensajeDetallesDetalle : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string identificadorField;

        private string faseField;

        private string errorField;

        private string estadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
                this.RaisePropertyChanged("Identificador");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_resp : object, System.ComponentModel.INotifyPropertyChanged
    {

        private ImportacionPesosPedidosType_respControlProceso controlProcesoField;

        private ImportacionPesosPedidosType_respCabecera cabeceraField;

        private ImportacionPesosPedidosType_respDetalleCabecera[] detallesCabeceraField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ImportacionPesosPedidosType_respControlProceso ControlProceso
        {
            get
            {
                return this.controlProcesoField;
            }
            set
            {
                this.controlProcesoField = value;
                this.RaisePropertyChanged("ControlProceso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosType_respCabecera Cabecera
        {
            get
            {
                return this.cabeceraField;
            }
            set
            {
                this.cabeceraField = value;
                this.RaisePropertyChanged("Cabecera");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DetalleCabecera", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosType_respDetalleCabecera[] DetallesCabecera
        {
            get
            {
                return this.detallesCabeceraField;
            }
            set
            {
                this.detallesCabeceraField = value;
                this.RaisePropertyChanged("DetallesCabecera");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProceso : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string codigoCompaniaField;

        private string codigoSistemaField;

        private string codigoServicioField;

        private string procesoField;

        private string resultadoField;

        private ImportacionPesosPedidosType_respControlProcesoRespuesta[] respuestaField;

        private ImportacionPesosPedidosType_respControlProcesoERP[] eRPField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CodigoCompania
        {
            get
            {
                return this.codigoCompaniaField;
            }
            set
            {
                this.codigoCompaniaField = value;
                this.RaisePropertyChanged("CodigoCompania");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CodigoSistema
        {
            get
            {
                return this.codigoSistemaField;
            }
            set
            {
                this.codigoSistemaField = value;
                this.RaisePropertyChanged("CodigoSistema");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string CodigoServicio
        {
            get
            {
                return this.codigoServicioField;
            }
            set
            {
                this.codigoServicioField = value;
                this.RaisePropertyChanged("CodigoServicio");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Proceso
        {
            get
            {
                return this.procesoField;
            }
            set
            {
                this.procesoField = value;
                this.RaisePropertyChanged("Proceso");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
                this.RaisePropertyChanged("Resultado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Respuesta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public ImportacionPesosPedidosType_respControlProcesoRespuesta[] Respuesta
        {
            get
            {
                return this.respuestaField;
            }
            set
            {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ERP", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public ImportacionPesosPedidosType_respControlProcesoERP[] ERP
        {
            get
            {
                return this.eRPField;
            }
            set
            {
                this.eRPField = value;
                this.RaisePropertyChanged("ERP");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoRespuesta : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string observacionField;

        private ImportacionPesosPedidosType_respControlProcesoRespuestaMensaje[] mensajeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Observacion
        {
            get
            {
                return this.observacionField;
            }
            set
            {
                this.observacionField = value;
                this.RaisePropertyChanged("Observacion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Mensaje", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosType_respControlProcesoRespuestaMensaje[] Mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
                this.RaisePropertyChanged("Mensaje");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoRespuestaMensaje : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string identificadorField;

        private string estadoField;

        private string faseField;

        private string errorField;

        private ImportacionPesosPedidosType_respControlProcesoRespuestaMensajeDetallesDetalle[] detallesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
                this.RaisePropertyChanged("Identificador");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Detalle", typeof(ImportacionPesosPedidosType_respControlProcesoRespuestaMensajeDetallesDetalle), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosType_respControlProcesoRespuestaMensajeDetallesDetalle[] Detalles
        {
            get
            {
                return this.detallesField;
            }
            set
            {
                this.detallesField = value;
                this.RaisePropertyChanged("Detalles");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoRespuestaMensajeDetallesDetalle : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string identificadorField;

        private string faseField;

        private string errorField;

        private string estadoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Identificador
        {
            get
            {
                return this.identificadorField;
            }
            set
            {
                this.identificadorField = value;
                this.RaisePropertyChanged("Identificador");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoERP : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string versionField;

        private ImportacionPesosPedidosType_respControlProcesoERPServidor[] servidorField;

        private ImportacionPesosPedidosType_respControlProcesoERPSesion[] sesionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Servidor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosType_respControlProcesoERPServidor[] Servidor
        {
            get
            {
                return this.servidorField;
            }
            set
            {
                this.servidorField = value;
                this.RaisePropertyChanged("Servidor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sesion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public ImportacionPesosPedidosType_respControlProcesoERPSesion[] Sesion
        {
            get
            {
                return this.sesionField;
            }
            set
            {
                this.sesionField = value;
                this.RaisePropertyChanged("Sesion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoERPServidor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nombreField;

        private string usuarioField;

        private string claveField;

        private string claveEncriptadaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ClaveEncriptada
        {
            get
            {
                return this.claveEncriptadaField;
            }
            set
            {
                this.claveEncriptadaField = value;
                this.RaisePropertyChanged("ClaveEncriptada");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoERPSesion : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string shellField;

        private string programaField;

        private ImportacionPesosPedidosType_respControlProcesoERPSesionParametrosSet[] parametrosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Shell
        {
            get
            {
                return this.shellField;
            }
            set
            {
                this.shellField = value;
                this.RaisePropertyChanged("Shell");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Programa
        {
            get
            {
                return this.programaField;
            }
            set
            {
                this.programaField = value;
                this.RaisePropertyChanged("Programa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Set", typeof(ImportacionPesosPedidosType_respControlProcesoERPSesionParametrosSet), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosType_respControlProcesoERPSesionParametrosSet[] Parametros
        {
            get
            {
                return this.parametrosField;
            }
            set
            {
                this.parametrosField = value;
                this.RaisePropertyChanged("Parametros");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respControlProcesoERPSesionParametrosSet : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nombreField;

        private string valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respCabecera : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string secuencialField;

        private string viajeCompletoField;

        private string fechaEntregaField;

        private string rutaEstandarField;

        private string almacenField;

        private string usuarioField;

        private string faseField;

        private string estadoField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Secuencial
        {
            get
            {
                return this.secuencialField;
            }
            set
            {
                this.secuencialField = value;
                this.RaisePropertyChanged("Secuencial");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ViajeCompleto
        {
            get
            {
                return this.viajeCompletoField;
            }
            set
            {
                this.viajeCompletoField = value;
                this.RaisePropertyChanged("ViajeCompleto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string FechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("FechaEntrega");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string RutaEstandar
        {
            get
            {
                return this.rutaEstandarField;
            }
            set
            {
                this.rutaEstandarField = value;
                this.RaisePropertyChanged("RutaEstandar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Almacen
        {
            get
            {
                return this.almacenField;
            }
            set
            {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosType_respDetalleCabecera : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string secuenciaSecuencialField;

        private string viajeCompletoField;

        private string ordenVentaField;

        private string conjuntoField;

        private string posicionField;

        private string numeroSecuenciaField;

        private string numeroSugerenciaField;

        private string rutaEstandarField;

        private string clienteField;

        private string secuenciaEntregaField;

        private string articuloField;

        private string almacenField;

        private string unidadAlmacenamientoField;

        private string cantidadUnidadStockField;

        private string cantidadUnidadAlmacenamientoField;

        private string pesoBrutoField;

        private string faseField;

        private string estadoField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string SecuenciaSecuencial
        {
            get
            {
                return this.secuenciaSecuencialField;
            }
            set
            {
                this.secuenciaSecuencialField = value;
                this.RaisePropertyChanged("SecuenciaSecuencial");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ViajeCompleto
        {
            get
            {
                return this.viajeCompletoField;
            }
            set
            {
                this.viajeCompletoField = value;
                this.RaisePropertyChanged("ViajeCompleto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string OrdenVenta
        {
            get
            {
                return this.ordenVentaField;
            }
            set
            {
                this.ordenVentaField = value;
                this.RaisePropertyChanged("OrdenVenta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Conjunto
        {
            get
            {
                return this.conjuntoField;
            }
            set
            {
                this.conjuntoField = value;
                this.RaisePropertyChanged("Conjunto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Posicion
        {
            get
            {
                return this.posicionField;
            }
            set
            {
                this.posicionField = value;
                this.RaisePropertyChanged("Posicion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string NumeroSecuencia
        {
            get
            {
                return this.numeroSecuenciaField;
            }
            set
            {
                this.numeroSecuenciaField = value;
                this.RaisePropertyChanged("NumeroSecuencia");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string NumeroSugerencia
        {
            get
            {
                return this.numeroSugerenciaField;
            }
            set
            {
                this.numeroSugerenciaField = value;
                this.RaisePropertyChanged("NumeroSugerencia");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string RutaEstandar
        {
            get
            {
                return this.rutaEstandarField;
            }
            set
            {
                this.rutaEstandarField = value;
                this.RaisePropertyChanged("RutaEstandar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string SecuenciaEntrega
        {
            get
            {
                return this.secuenciaEntregaField;
            }
            set
            {
                this.secuenciaEntregaField = value;
                this.RaisePropertyChanged("SecuenciaEntrega");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string Articulo
        {
            get
            {
                return this.articuloField;
            }
            set
            {
                this.articuloField = value;
                this.RaisePropertyChanged("Articulo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string Almacen
        {
            get
            {
                return this.almacenField;
            }
            set
            {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string UnidadAlmacenamiento
        {
            get
            {
                return this.unidadAlmacenamientoField;
            }
            set
            {
                this.unidadAlmacenamientoField = value;
                this.RaisePropertyChanged("UnidadAlmacenamiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string CantidadUnidadStock
        {
            get
            {
                return this.cantidadUnidadStockField;
            }
            set
            {
                this.cantidadUnidadStockField = value;
                this.RaisePropertyChanged("CantidadUnidadStock");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string CantidadUnidadAlmacenamiento
        {
            get
            {
                return this.cantidadUnidadAlmacenamientoField;
            }
            set
            {
                this.cantidadUnidadAlmacenamientoField = value;
                this.RaisePropertyChanged("CantidadUnidadAlmacenamiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string PesoBruto
        {
            get
            {
                return this.pesoBrutoField;
            }
            set
            {
                this.pesoBrutoField = value;
                this.RaisePropertyChanged("PesoBruto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoERP : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string versionField;

        private ImportacionPesosPedidosTypeControlProcesoERPServidor[] servidorField;

        private ImportacionPesosPedidosTypeControlProcesoERPSesion[] sesionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Servidor", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public ImportacionPesosPedidosTypeControlProcesoERPServidor[] Servidor
        {
            get
            {
                return this.servidorField;
            }
            set
            {
                this.servidorField = value;
                this.RaisePropertyChanged("Servidor");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Sesion", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public ImportacionPesosPedidosTypeControlProcesoERPSesion[] Sesion
        {
            get
            {
                return this.sesionField;
            }
            set
            {
                this.sesionField = value;
                this.RaisePropertyChanged("Sesion");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoERPServidor : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nombreField;

        private string usuarioField;

        private string claveField;

        private string claveEncriptadaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string Clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
                this.RaisePropertyChanged("Clave");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string ClaveEncriptada
        {
            get
            {
                return this.claveEncriptadaField;
            }
            set
            {
                this.claveEncriptadaField = value;
                this.RaisePropertyChanged("ClaveEncriptada");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoERPSesion : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string shellField;

        private string programaField;

        private ImportacionPesosPedidosTypeControlProcesoERPSesionParametrosSet[] parametrosField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Shell
        {
            get
            {
                return this.shellField;
            }
            set
            {
                this.shellField = value;
                this.RaisePropertyChanged("Shell");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Programa
        {
            get
            {
                return this.programaField;
            }
            set
            {
                this.programaField = value;
                this.RaisePropertyChanged("Programa");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Set", typeof(ImportacionPesosPedidosTypeControlProcesoERPSesionParametrosSet), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
        public ImportacionPesosPedidosTypeControlProcesoERPSesionParametrosSet[] Parametros
        {
            get
            {
                return this.parametrosField;
            }
            set
            {
                this.parametrosField = value;
                this.RaisePropertyChanged("Parametros");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeControlProcesoERPSesionParametrosSet : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string nombreField;

        private string valorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Nombre
        {
            get
            {
                return this.nombreField;
            }
            set
            {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string Valor
        {
            get
            {
                return this.valorField;
            }
            set
            {
                this.valorField = value;
                this.RaisePropertyChanged("Valor");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeCabecera : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string secuencialField;

        private string viajeCompletoField;

        private string fechaEntregaField;

        private string rutaEstandarField;

        private string almacenField;

        private string usuarioField;

        private string faseField;

        private string estadoField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string Secuencial
        {
            get
            {
                return this.secuencialField;
            }
            set
            {
                this.secuencialField = value;
                this.RaisePropertyChanged("Secuencial");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ViajeCompleto
        {
            get
            {
                return this.viajeCompletoField;
            }
            set
            {
                this.viajeCompletoField = value;
                this.RaisePropertyChanged("ViajeCompleto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string FechaEntrega
        {
            get
            {
                return this.fechaEntregaField;
            }
            set
            {
                this.fechaEntregaField = value;
                this.RaisePropertyChanged("FechaEntrega");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string RutaEstandar
        {
            get
            {
                return this.rutaEstandarField;
            }
            set
            {
                this.rutaEstandarField = value;
                this.RaisePropertyChanged("RutaEstandar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Almacen
        {
            get
            {
                return this.almacenField;
            }
            set
            {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string Usuario
        {
            get
            {
                return this.usuarioField;
            }
            set
            {
                this.usuarioField = value;
                this.RaisePropertyChanged("Usuario");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos")]
    public partial class ImportacionPesosPedidosTypeDetalleCabecera : object, System.ComponentModel.INotifyPropertyChanged
    {

        private string secuenciaSecuencialField;

        private string viajeCompletoField;

        private string ordenVentaField;

        private string conjuntoField;

        private string posicionField;

        private string numeroSecuenciaField;

        private string numeroSugerenciaField;

        private string rutaEstandarField;

        private string clienteField;

        private string secuenciaEntregaField;

        private string articuloField;

        private string almacenField;

        private string unidadAlmacenamientoField;

        private string cantidadUnidadStockField;

        private string cantidadUnidadAlmacenamientoField;

        private string pesoBrutoField;

        private string faseField;

        private string estadoField;

        private string errorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string SecuenciaSecuencial
        {
            get
            {
                return this.secuenciaSecuencialField;
            }
            set
            {
                this.secuenciaSecuencialField = value;
                this.RaisePropertyChanged("SecuenciaSecuencial");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string ViajeCompleto
        {
            get
            {
                return this.viajeCompletoField;
            }
            set
            {
                this.viajeCompletoField = value;
                this.RaisePropertyChanged("ViajeCompleto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string OrdenVenta
        {
            get
            {
                return this.ordenVentaField;
            }
            set
            {
                this.ordenVentaField = value;
                this.RaisePropertyChanged("OrdenVenta");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public string Conjunto
        {
            get
            {
                return this.conjuntoField;
            }
            set
            {
                this.conjuntoField = value;
                this.RaisePropertyChanged("Conjunto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 4)]
        public string Posicion
        {
            get
            {
                return this.posicionField;
            }
            set
            {
                this.posicionField = value;
                this.RaisePropertyChanged("Posicion");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 5)]
        public string NumeroSecuencia
        {
            get
            {
                return this.numeroSecuenciaField;
            }
            set
            {
                this.numeroSecuenciaField = value;
                this.RaisePropertyChanged("NumeroSecuencia");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 6)]
        public string NumeroSugerencia
        {
            get
            {
                return this.numeroSugerenciaField;
            }
            set
            {
                this.numeroSugerenciaField = value;
                this.RaisePropertyChanged("NumeroSugerencia");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 7)]
        public string RutaEstandar
        {
            get
            {
                return this.rutaEstandarField;
            }
            set
            {
                this.rutaEstandarField = value;
                this.RaisePropertyChanged("RutaEstandar");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 8)]
        public string Cliente
        {
            get
            {
                return this.clienteField;
            }
            set
            {
                this.clienteField = value;
                this.RaisePropertyChanged("Cliente");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 9)]
        public string SecuenciaEntrega
        {
            get
            {
                return this.secuenciaEntregaField;
            }
            set
            {
                this.secuenciaEntregaField = value;
                this.RaisePropertyChanged("SecuenciaEntrega");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 10)]
        public string Articulo
        {
            get
            {
                return this.articuloField;
            }
            set
            {
                this.articuloField = value;
                this.RaisePropertyChanged("Articulo");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 11)]
        public string Almacen
        {
            get
            {
                return this.almacenField;
            }
            set
            {
                this.almacenField = value;
                this.RaisePropertyChanged("Almacen");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 12)]
        public string UnidadAlmacenamiento
        {
            get
            {
                return this.unidadAlmacenamientoField;
            }
            set
            {
                this.unidadAlmacenamientoField = value;
                this.RaisePropertyChanged("UnidadAlmacenamiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 13)]
        public string CantidadUnidadStock
        {
            get
            {
                return this.cantidadUnidadStockField;
            }
            set
            {
                this.cantidadUnidadStockField = value;
                this.RaisePropertyChanged("CantidadUnidadStock");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 14)]
        public string CantidadUnidadAlmacenamiento
        {
            get
            {
                return this.cantidadUnidadAlmacenamientoField;
            }
            set
            {
                this.cantidadUnidadAlmacenamientoField = value;
                this.RaisePropertyChanged("CantidadUnidadAlmacenamiento");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 15)]
        public string PesoBruto
        {
            get
            {
                return this.pesoBrutoField;
            }
            set
            {
                this.pesoBrutoField = value;
                this.RaisePropertyChanged("PesoBruto");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 16)]
        public string Fase
        {
            get
            {
                return this.faseField;
            }
            set
            {
                this.faseField = value;
                this.RaisePropertyChanged("Fase");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 17)]
        public string Estado
        {
            get
            {
                return this.estadoField;
            }
            set
            {
                this.estadoField = value;
                this.RaisePropertyChanged("Estado");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 18)]
        public string Error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ImportacionPesosPedidos_OSRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos", Order = 0)]
        public netServicioSAP.ServiceReference1.ImportacionPesosPedidosType ImportacionPesosPedidos;

        public ImportacionPesosPedidos_OSRequest()
        {
        }

        public ImportacionPesosPedidos_OSRequest(netServicioSAP.ServiceReference1.ImportacionPesosPedidosType ImportacionPesosPedidos)
        {
            this.ImportacionPesosPedidos = ImportacionPesosPedidos;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ImportacionPesosPedidos_OSResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://pronaca.com/INT011/mms/1.0/ImportacionPesosPedidos", Order = 0)]
        public netServicioSAP.ServiceReference1.ImportacionPesosPedidosType_resp ImportacionPesosPedidos_resp;

        public ImportacionPesosPedidos_OSResponse()
        {
        }

        public ImportacionPesosPedidos_OSResponse(netServicioSAP.ServiceReference1.ImportacionPesosPedidosType_resp ImportacionPesosPedidos_resp)
        {
            this.ImportacionPesosPedidos_resp = ImportacionPesosPedidos_resp;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportacionPesosPedidos_OSChannel : netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportacionPesosPedidos_OSClient : System.ServiceModel.ClientBase<netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS>, netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS
    {

        public ImportacionPesosPedidos_OSClient()
        {
        }

        public ImportacionPesosPedidos_OSClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public ImportacionPesosPedidos_OSClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ImportacionPesosPedidos_OSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public ImportacionPesosPedidos_OSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS.ImportacionPesosPedidos_OS(netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest request)
        {
            return base.Channel.ImportacionPesosPedidos_OS(request);
        }

        public netServicioSAP.ServiceReference1.ImportacionPesosPedidosType_resp ImportacionPesosPedidos_OS(netServicioSAP.ServiceReference1.ImportacionPesosPedidosType ImportacionPesosPedidos)
        {
            netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest inValue = new netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest();
            inValue.ImportacionPesosPedidos = ImportacionPesosPedidos;
            netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse retVal = ((netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS)(this)).ImportacionPesosPedidos_OS(inValue);
            return retVal.ImportacionPesosPedidos_resp;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse> netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS.ImportacionPesosPedidos_OSAsync(netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest request)
        {
            return base.Channel.ImportacionPesosPedidos_OSAsync(request);
        }

        public System.Threading.Tasks.Task<netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSResponse> ImportacionPesosPedidos_OSAsync(netServicioSAP.ServiceReference1.ImportacionPesosPedidosType ImportacionPesosPedidos)
        {
            netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest inValue = new netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OSRequest();
            inValue.ImportacionPesosPedidos = ImportacionPesosPedidos;
            return ((netServicioSAP.ServiceReference1.ImportacionPesosPedidos_OS)(this)).ImportacionPesosPedidos_OSAsync(inValue);
        }
    }
}
